# Generated by Django 2.2.1 on 2019-05-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupe',
            fields=[
                ('naziv_grupe', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pocetak_rv', models.TimeField()),
                ('kraj_rv', models.TimeField()),
                ('radni_dani', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Grupe',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id_terminala', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv_terminala', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Terminali',
            },
        ),
        migrations.CreateModel(
            name='Tip_eventa',
            fields=[
                ('event_number', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Tipovi Eventa',
            },
        ),
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('pin', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('card_number', models.IntegerField(unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profilneslike')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Grupe')),
            ],
            options={
                'verbose_name_plural': 'Zaposleni',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_picture', models.ImageField(blank=True, upload_to='eventslike')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tip_eventa')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Terminal')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Zaposleni')),
            ],
            options={
                'verbose_name_plural': 'Eventi',
            },
        ),
    ]
